"""add user email avatar, movie tagline, collection to_dict

Revision ID: 7643b9729fe3
Revises:
Create Date: 2026-05-15 09:42:33.029060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7643b9729fe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_similarity', schema=None) as batch_op:
        batch_op.create_index('idx_similarity_movie_score', ['movie_id', 'score'], unique=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index('idx_ratings_movie_rating', ['movie_id', 'rating'], unique=False)
        batch_op.create_index('idx_ratings_user_time', ['user_id', 'timestamp'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_column('avatar')
        batch_op.drop_column('email')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index('idx_ratings_user_time')
        batch_op.drop_index('idx_ratings_movie_rating')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('tagline')

    with op.batch_alter_table('movie_similarity', schema=None) as batch_op:
        batch_op.drop_index('idx_similarity_movie_score')

    # ### end Alembic commands ###
